env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:jest-formatting/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  # Require a whitespace at the beginning of a comment
  spaced-comment:
    - error
    - always

  # Maximum line length for comments except trailing comments
  max-len:
    - error
    - comments: 120
      code: 200 # Set to not conflict with Prettier
      ignoreTrailingComments: true
      ignoreUrls: true

  # Require braces around blocks
  curly:
    - error
    - all

  # Require parentheses around arrow function arguments
  arrow-parens:
    - error
    - always

  # Require blank line before certain statements
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: function
    - blankLine: always
      prev: '*'
      next: class
    - blankLine: always
      prev: '*'
      next: export
    # Ignore consecutive export statements
    - blankLine: any
      prev: export
      next: export
    - blankLine: always
      prev: '*'
      next: return
    - blankLine: always
      prev: '*'
      next: break
    - blankLine: always
      prev: '*'
      next: continue
    - blankLine: always
      prev: '*'
      next: throw

  # eslint-plugin-react rules

  # Require props to be sorted
  react/jsx-sort-props:
    - error
    - callbacksLast: true
      shorthandFirst: true

  # Omit boolean prop value when set to true
  react/jsx-boolean-value:
    - error
    - never

  # Require self closing tags in JSX/HTML
  react/self-closing-comp:
    - error
    - component: true
      html: true

  # Require PascalCase for user-defined JSX components
  react/jsx-pascal-case:
    - error

  react/prop-types:
    - off

  # Disallow unnecessary curly braces in JSX
  react/jsx-curly-brace-presence:
    - error
    - never

  # "React" must be in scope when using JSX
  react/react-in-jsx-scope:
    - off
