name: Feature Request
description: File a feature request
title: '[Feature]: '
labels: ['Feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature request report!

  - type: textarea
    id: what-happened
    attributes:
      label: Suggest an idea for this project ?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Please provide an example screenshot
      placeholder: screenshot
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Checklist
      multiple: true
      options:
        - I have searched the existing issues to make sure this is not a duplicate
        - I have checked the documentation and found no answer
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this feature request, you agree to follow our [Code of Conduct](
        https://github.com/OpenSource-Journey/Your-Github-Contributions/blob/main/CODE_OF_CONDUCT.md))
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
