name: Contributor Analytics Workflow

on:
  push:
    branches:
      - main

jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Contributor Analytics
        uses: Sachin-chaurasiya/contributor-analytics-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
